# Generated by Django 4.0.5 on 2022-06-22 10:26

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=todo.models.upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
